### PR TITLE
Updated IPRiskList and added DomainRiskList

### PR DESCRIPTION
**Pull request by Jonas337**
Recorded future has updated their API to V2, and will soon deprecate v1.

The IPRiskList class has been updated to v2, and a new class DomainRiskList, has also been added using the new V2 API

### CODE REVIEW

**Comment by jtschichold** [comment]
Hi @Jonas337,
thanks !

Couple of things before merging:
Could you add your name to the AUTHORS file ?
Could you also explicitly accept the Apache license ? ("I accept it" in a comment to this PR works :-))

**Comment by Jonas337** [comment]
I accept the apache license

**Comment by jtschichold** [comment]
Almost there !

Please, could you fix the following PEP8 formatting errors ?
```
$ flake8 minemeld/ft/recordedfuture.py
minemeld/ft/recordedfuture.py:127:44: W291 trailing whitespace
minemeld/ft/recordedfuture.py:130:61: W291 trailing whitespace
minemeld/ft/recordedfuture.py:131:1: E101 indentation contains mixed spaces and tabs
minemeld/ft/recordedfuture.py:131:1: W191 indentation contains tabs
minemeld/ft/recordedfuture.py:131:4: E131 continuation line unaligned for hanging indent
minemeld/ft/recordedfuture.py:132:1: W293 blank line contains whitespace
minemeld/ft/recordedfuture.py:132:1: E101 indentation contains mixed spaces and tabs
minemeld/ft/recordedfuture.py:159:1: E302 expected 2 blank lines, found 0
minemeld/ft/recordedfuture.py:239:44: W291 trailing whitespace
minemeld/ft/recordedfuture.py:242:65: W291 trailing whitespace
minemeld/ft/recordedfuture.py:243:1: E101 indentation contains mixed spaces and tabs
minemeld/ft/recordedfuture.py:243:1: W191 indentation contains tabs
minemeld/ft/recordedfuture.py:243:4: E131 continuation line unaligned for hanging indent
minemeld/ft/recordedfuture.py:244:1: W293 blank line contains whitespace
minemeld/ft/recordedfuture.py:244:1: E101 indentation contains mixed spaces and tabs
minemeld/ft/recordedfuture.py:272:1: W391 blank line at end of file
```

You can read here about MineMeld Coding Style (PEP8-ish):
https://github.com/PaloAltoNetworks/minemeld/wiki/Contributing-to-MineMeld#coding-style

Thanks!

**Comment by jtschichold** [comment]
Tested this and works. There are some changes to be made, but I will take care of them

**Pull request merged**
